Refactor: Creates Task context instead of passing as props
LukeberryPi/phived pull request #22
Opened 2023-03-19 16:40 UTC by Nick-Gabe

## Solves #21 

## What problem the PR solves?
The tasks state was being created on App and passed to components who needed it, and it is fine, however it may not be scalable if the project grows or becomes more componentized, since if a deep component wants any data from tasks, it would become a prop drilling.

Also since some functions like clearTasks were being created on separate components, that could lead to some typescript issues like mentioning a single type in multiple places, and then struggling to replace all of them if that type changes in the future.

## What solution the PR gives?
It creates a context called `TasksContext`, that exposes the `tasks, setTasks` state, along with some useful custom methods like `changeTask` to change one specific task, `resetTasks` to reset one or more tasks, along with automatically updating localstorage when any change happens, so other components don't take this responsibility.

It also centers the types in one place, mentioning the Task, Tasks, and methods typings, therefore if any external component needs, it can import this type and avoid conflicting types.

Also every component that previously depended on the props were updated to match this new approach.

2023-03-19 17:08 UTC, LukeberryPi commented
nick, awesome pr! i learned a lot just skimming through the diff.

one thing caught my eye: your proposal is that we create a method resetTasks, that either: 

- receives an index, understands that a single task is being completed, and updates the task list accordingly.
- doesn't receive an index, and understands that this means the user wants the entire task list cleared.

i feel like this could be improved by creating two methods:

completeTask => that always receives an index (for the task that is being completed)
clearTasks => that receives no arguments, and is simply a "task list reset"

what do you say?

2023-03-19 17:17 UTC, Nick-Gabe commented
@LukeberryPi good suggestion! I haven't thought about splitting it into two different methods.
Honestly now that you said, resetTasks for completing a single task really seems strange haha. I'll implement it 👍

2023-03-19 18:00 UTC, noghartt approved these changes

2023-03-19 18:00 UTC, noghartt commented on src/components/Header/Header.tsx
> +          onClick={() => resetTasks()}
```suggestion
          onClick={resetTasks}
```

2023-03-19 18:25 UTC, Nick-Gabe commented on src/contexts/index.ts
> +export { TasksContext, TasksContextProvider } from "./TasksContext";
I was following the patterns of already existing files, having each folder with an index where the items inside it are exported

2023-03-19 18:27 UTC, noghartt commented on src/contexts/index.ts
> +export { TasksContext, TasksContextProvider } from "./TasksContext";
I think that @vit0rr was removing these files, in general, `index.tsx` file is a poor abstraction IMO.

2023-03-19 18:27 UTC, Nick-Gabe commented on src/contexts/TasksContext/index.ts
> +export type { TasksContextTypes } from "./TasksContext.types"
I think having an index inside each context folder is better for readability, otherwise the index file of the group of contexts folder would get bigger over time

2023-03-19 18:33 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContext.types.ts
> +export type Tasks = [Task, Task, Task, Task, Task];
A typed array is an indetermined number of items of a specified type, but as the current architecture, we have a fixed number of tasks and for me doesn't make sense setting it to `Task[]` and implicitly saying any quantity of items is valid, when in reality having 0 or 10 items is not even a possible scenario yet.

If in the future the user gets able to add tasks infinitely I agree about changing, but as of now I think a tuple works better to transmit the idea of a fixed length.

2023-03-19 18:36 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContext.types.ts
To follow the pattern of the project, whereas you have an index file to export the files inside the folder, the components, and then a *.types.ts incase any type is being used.

Basically just to convey to the developer it is a file just to hold types, although I think `d.ts` may work better for this purpose.

2023-03-19 18:38 UTC, Nick-Gabe commented on src/components/Header/Header.tsx
> +          onClick={() => resetTasks()}
This file got updated and resetTasks isn't used anymore, but previously the arrow function was needed because resetTasks accepted parameters, and by using `onClick={resetTasks}` they would end up getting wrongfully sent from the event and causing bugs, so the arrow function explicitly said no parameters should be sent.

2023-03-19 18:39 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +import { useLocalStorage } from "src/hooks";
Why?

2023-03-19 18:41 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContext.types.ts
@LukeberryPi what do you think about using definition type files instead of the current `types.ts`?
Here's the documentation about it, they don't generate JS output and are only used for typechecking purposes.
https://www.typescriptlang.org/docs/handbook/2/type-declarations.html#dts-files

2023-03-19 18:44 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +import { useLocalStorage } from "src/hooks";
Ok got it, saw the issue about removing index files

2023-03-19 18:45 UTC, Nick-Gabe commented on src/contexts/index.ts
> +export { TasksContext, TasksContextProvider } from "./TasksContext";
oh ok ok, I just saw the issue about that, I'll remove the index's then

2023-03-19 18:47 UTC, Allyhere commented
@Nick-Gabe, currently we have 2 problems with the Task component
- `tasks` state is controlled by App, so App re-renders on every `tasks` change
- `<Header>` component mutate `tasks` state hosted in the parent component, on `clearTask` action, the App, Header and Tasks components re-renders.

These are problems that I'm currently working on in #10, does your solution tacke them? Can we work together in this improvment to mitigate possible conflicts?

2023-03-19 18:53 UTC, Nick-Gabe commented
@Allyhere Yes, now tasks aren't controlled by app anymore, they are controlled by an external context, so when it changes, only direct dependents of it get re-rendered (Head/Header/Tasks)
And now the method that clears the tasks, called inside Header, doesn't trigger any re-render on the app.

And of course, we can work together on this and fix conflicts as needed.
I think this one can be merged first, and then I can help with yours.

2023-03-19 21:44 UTC, Allyhere commented
@LukeberryPi I'll create a new PR for A11y improvements taking into account what you said in your comment and wait for for @Nick-Gabe PR to be merged for further performance related improvements if needed, what yall think?

2023-03-19 22:41 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContext.types.ts
I'll rewrite this as an issue later

2023-03-19 22:45 UTC, Nick-Gabe commented
@LukeberryPi @noghartt The changes have been made about the commented points. Please check if anything should be changed 😄

2023-03-20 10:58 UTC, nidib requested changes
Really nice PR though! Love contexts ❤️

Just wanted to share these thoughts.

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContext.types.ts
> +export type TasksContextTypes = {
#minor I think `TaskContextType` in singular makes more sense

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +      value={{
since this will affect everything, using useMemo for the value and useCallbacks for callbacks could save us some unnecessary rerenders

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +    setTasks(initialState.tasks);
i think there might be a bug hidden here. There is a chance that the state will be changed to the same array reference, and react does not like that.

That will happen if the tasks are cleared when no task is actually added.

We can just avoid that by instead of using a fixed array reference, use fuction that always get us a new instance of it

2023-03-20 10:58 UTC, nidib commented on src/components/Tasks/Tasks.tsx
> +  const { tasks, changeTask, completeTask } = useContext(TasksContext);
I think we should export `useTasksContext` so we don't have to manually use the context every time

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContext.tsx
> +  tasks: Array(5).fill("")
when using .fill() we lose inferred typing. passing <string> to the Array constructor should solve it

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +    const newTasklist = taskCopy.map((task, index) =>
we don't need to iterate over all tasks just to change some index we already know.

i suggest to mutate taskCopy since it is safely copied already. Something like

```javascript
taskCopy[taskIndex] = newValue;

setTasks(taskCopy);
```

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +  const changeTask: TasksContextTypes['changeTask'] = (taskIndex, newValue) => {
i like typing context methods, but since value on the provider expect those types, we might make this visually simpler by inferring the callback types

2023-03-20 10:58 UTC, nidib commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +    setTasks([...ongoingTasks, initialState.tasks[index]] as Tasks);
second param of setTasks I would set it to be a simple empty string instead of accessing that by index

2023-03-20 11:16 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +    const newTasklist = taskCopy.map((task, index) =>
good suggestion! thanks!

2023-03-20 11:19 UTC, Nick-Gabe commented on src/contexts/TasksContext/TasksContextProvider.tsx
> +    setTasks([...ongoingTasks, initialState.tasks[index]] as Tasks);
I was thinking about centering the reference incase it gets changed in the future, but it is quite overengineering taking these into account.

I'll do some changes here regarding referencing those initialValuea

2023-03-20 11:20 UTC, Nick-Gabe commented
@nidib perfect suggestions! thank you for the contribution, I'll do the needed changes when on my spare time :)

2023-03-21 02:25 UTC, Nick-Gabe commented
@LukeberryPi Conflicts fixed and suggestions implemented

2023-03-21 11:17 UTC, LukeberryPi approved these changes
huge, really happy about these changes

2023-03-21 11:18 UTC, merged

2023-03-21 14:34 UTC, nidib reviewed
👍🏾