Improve Head component
LukeberryPi/phived pull request #31
Opened 2023-03-20 23:48 UTC by JoaoVictor6

Hello! Im João([@PrazerJo](https://twitter.com/PrazerJo)). I saw this project on my feed and I was interested. Here are my 5 cents on this project. I hope I can contribute more :)
## What problem the PR solves?
When reading this component, I see some problems with performance and readability. When a state is updated, the Component where this state is initialized has to render, this makes the component render two times always. How did I make resolve this? simple: [You do Not Need an Effect](https://react.dev/learn/you-might-not-need-an-effect).

## What solution the PR gives?
I removed the useEffect and unnecessary state, Keep It Simple

2023-03-21 15:03 UTC, nidib requested changes
Really nice PR. The useEffect is really not necessary.

Just these few considerations for it to be a go on my end

2023-03-21 15:54 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +        [titlePrefix, defaultTitle].join(' ')
Make more sense. I was very sleepy when made 😆

2023-03-21 18:53 UTC, nidib requested changes

2023-03-21 18:53 UTC, nidib commented on src/components/Head/Head.tsx
> +        `${titlePrefix} ${BASE_PAGE_TITLE}`
#review
- if there is no title prefix, it'll have an empty character before the title. We need to trim this string.

#suggestion
- My suggestion to keep it bit cleaner:
```js
const title = `${titlePrefix} ${BASE_PAGE_TITLE}`.trim();
const iconPath = `/${enableTasks.length ? ALERT_ICON : DEFAULT_ICON}`;
```

```jsx
<title>{title}</title>
<link 
        rel="icon" 
        type="image/x-icon" 
        href={iconPath} 
/>
```

2023-03-21 19:15 UTC, Nick-Gabe commented
@JoaoVictor6 Please click on "resolve" when you resolve any comment, just for us to know what you already fixed or not, thanks :)

2023-03-21 19:25 UTC, Nick-Gabe requested changes

2023-03-21 19:25 UTC, Nick-Gabe commented on src/components/Head/Head.tsx
> +const BASE_PAGE_TITLE = "phived - the anti-procrastination to-do list"
I suggest putting those in a separate file, for example
```typescript
// headConstants.ts
export const headConstants = {
  icons: {
    default: "favicon-default.ico",
    alert: "favicon-alert.ico"
  },
  baseTitle: "phived - the anti-procrastination to-do list"
}
```

2023-03-21 19:25 UTC, Nick-Gabe commented on src/components/Head/Head.tsx
> +  const enableTasks = tasks.filter(Boolean)
Maybe renaming this variable to "pendingTasks"

2023-03-21 19:25 UTC, Nick-Gabe commented on src/components/Head/Head.tsx
> +        `${titlePrefix} ${BASE_PAGE_TITLE}`
There's no need to use Javascript template string here inside the title, one solution is to do as @nidib said

2023-03-21 21:17 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +const BASE_PAGE_TITLE = "phived - the anti-procrastination to-do list"
made :) I like to use constants' names in uppercase by convention, but I don't know if it is valid for this project

2023-03-21 21:18 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +  const enableTasks = tasks.filter(Boolean)
done :)

2023-03-21 21:18 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +        `${titlePrefix} ${BASE_PAGE_TITLE}`
done :)

2023-03-21 21:19 UTC, JoaoVictor6 commented
> Thank you for addressing the changes, everything good! :D

It was really cool, I hope I can contribute more :)

2023-03-21 22:39 UTC, nidib requested changes

2023-03-21 22:39 UTC, nidib commented on src/components/Head/Head.tsx
> +import { headConstants } from "./headConstants";
we still don't have a github workflow to run linting and soon to have tests. But if you run `npm run lint`it should throw an error due to this relative import.

I suggest to run the lint and fix possible errors

2023-03-23 00:17 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +import { headConstants } from "./headConstants";
![image](https://user-images.githubusercontent.com/68869379/227066846-dd221499-038c-4720-afb3-414e6c03cffb.png)
I fixed that, but the lint script is broken :/

2023-03-23 00:18 UTC, nidib commented on src/components/Head/Head.tsx
> +import { headConstants } from "./headConstants";
Just checking, but did you npm install everything? There were lib updates in between PRs

2023-03-23 00:24 UTC, JoaoVictor6 commented on src/components/Head/Head.tsx
> +import { headConstants } from "./headConstants";
with `npm ci` the script worked!

2023-03-23 00:27 UTC, nidib approved these changes
lgtm

2023-03-23 17:21 UTC, LukeberryPi approved these changes
lgtm

2023-03-23 17:22 UTC, merged