adding resize-feature
LukeberryPi/phived pull request #41
Opened 2023-03-27 22:22 UTC by YuriSamp

I added the 'react-resize-detector' npm package and used the useEffect hook to store the width in localStorage.

2023-03-27 23:12 UTC, Nick-Gabe requested changes

2023-03-27 23:12 UTC, Nick-Gabe commented on src/components/Tasks/Tasks.tsx
> +      localStorage.setItem("width", String(width));
Converting to string isn't needed, it is done automatically

2023-03-27 23:12 UTC, Nick-Gabe commented on src/components/Tasks/Tasks.tsx
> +  const widthInStorage = localStorage.getItem("width");
I think you can use the custom hook useLocalStorage instead
const [storedWidth, setStoredWidth] = useLocalStorage("width", "");

2023-03-27 23:12 UTC, Nick-Gabe commented on src/components/Tasks/Tasks.tsx
> +
according to the package docs, you can pass a "onResize" function that is triggered everytime a resize happens. Is this useEffect really needed?

Maybe we can use as suggested in the docs
```ts
const onResize = useCallback((width: number) => {
  setStoredWidth(width)
}, []);

useResizeDetector({ onResize })
```

2023-03-28 03:32 UTC, YuriSamp commented on src/components/Tasks/Tasks.tsx
> +      localStorage.setItem("width", String(width));
But TypeScript was complaining, so I had to do that.

2023-03-28 03:33 UTC, YuriSamp commented on src/components/Tasks/Tasks.tsx
> +
For some reason, this caused more bugs than it solved our problem, so I prefer to use useEffect because I feel it's safer to do this pull request.

2023-03-28 03:34 UTC, YuriSamp commented on src/components/Tasks/Tasks.tsx
> +  const widthInStorage = localStorage.getItem("width");
This is a nice one, I added the hook in my new commit

2023-03-28 15:40 UTC, LukeberryPi commented
is there anyway to style this guy? 
![image](https://user-images.githubusercontent.com/98068247/228292211-2893cbb7-e9cb-4739-9a83-c14b906e3cbe.png)

it's tough to see in dark mode

2023-03-28 19:18 UTC, LukeberryPi requested changes

2023-03-28 19:23 UTC, YuriSamp commented on src/components/Tasks/Tasks.tsx
> +  const { width, height, ref } = useResizeDetector();
i will fix this

2023-03-28 19:23 UTC, YuriSamp commented on src/components/Tasks/Tasks.tsx
> +      style={{ width: storedWidth + "px" }}
I tried multiple times, but I couldn't make it work. Also, Tailwind transforms itself into CSS at build time, so I'm not sure if this is appropriate.

2023-03-28 19:53 UTC, LukeberryPi approved these changes
lgtm

2023-03-28 19:53 UTC, merged